### ISSUE TITLE
The SafeStr module does not expose `SafeStr`

### ISSUE THREAD

**Issue by normanjaeckel** [Hasnep/roc-html#10]
The `Html.roc`interface wants to import `SafeStr` from the module `SafeStr`, which does not work, because it is not exposed. I do not understand why this wasn't a problem until I updated to the new roc nightly today (my last version was from April 15).

Thanks in advance for having a short look at this.

**Comment by Hasnep** [comment]
Thanks for reporting, the module system was overhauled in the latest nightly, see [this Zulip thread](https://roc.zulipchat.com/#narrow/stream/397893-announcements/topic/New.20module.20headers.20and.20imports/near/436899736) for more info. I'll see if I can release a fixed version in a few hours 👍

**Comment by Hasnep** [comment]
The new release [v0.5.0](https://github.com/Hasnep/roc-html/releases/tag/v0.5.0) should fix this. Let me know if you still have any problems :) Thanks again for alerting me to this

**Comment by normanjaeckel** [comment]
Yes looks good. Thank you very much.
