### ISSUE TITLE
`<br>` can't have a closing tag

### ISSUE THREAD

**Issue by adrian4096** [Hasnep/roc-html#8]
The resutlt of
```roc
Html.br [] []
```
is
```html
<br></br>
```
which Firefox renders as 
```html
<br><br>
```
- the correct fix is to add support for elements that need no closing.
- the quick fix is to replace the `br` function with
    `Html.dangerouslyIncludeUnescapedHtml "<br>"`.

**Comment by Hasnep** [comment]
Thanks for reporting @adrian4096, fixed in #9. I used the self-closing syntax for compatibility with XHTML, so `br []` will render as `</br>` which the browser will interpret as `<br>`.
